version: "3.2"

services:
  api-gateway:
    image: itl-teams/api-gateway:latest
    build: ./api
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"

  account-and-signature:
    container_name: account-and-signature
    restart: unless-stopped
    image: itl-teams/php:latest
    build: ./services/account-and-signature
    env_file:
      - ".env"
    volumes:
      - ./services/account-and-signature/public:/var/www/html
      - ./services/account-and-signature/app:/var/www/app

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ./services/mysql:/docker-entrypoint-initdb.d
    env_file:
      - ".env"
