version: "3.2"

services:
  api-gateway:
    image: itl-teams/api-gateway:latest
    build: ./api/example
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"

  node-example:
    image: itl-teams/node-example:dev
    build:
      context: ./services/node-example
      dockerfile: Dockerfile.dev
    container_name: node-example
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - APP_NAME=Example Node/Express App
      - DEV_PORT=3000
    env_file:
      - "example.env"
    volumes:
      - ./services/node-example/src:/home/app/src

  php-example:
    container_name: php-example
    restart: unless-stopped
    image: itl-teams/php:latest
    build: ./services/php-example
    ports:
      - "8081:80"
    env_file:
      - "example.env"
    volumes:
      - ./services/php-example/public:/var/www/html
      - ./services/php-example/app:/var/www/app

  database-example:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-example
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - ./services/mysql/example:/docker-entrypoint-initdb.d
    env_file:
      - "example.env"
